
services:
  log-analyzer:
    build:
      context: .
      dockerfile: Dockerfile.yml
      args:
        - API_KEY=${GEMINI_API_KEY}
    ports:
      - "${APP_PORT:-8080}:80"
    environment:
      - API_KEY=${GEMINI_API_KEY}
    restart: always
    # Убедитесь, что сервис loki описан здесь или находится в той же внешней сети
