
services:
  log-analyzer:
    build:
      context: .
      dockerfile: Dockerfile.yml
      network: host
      args:
        - API_KEY=${GEMINI_API_KEY}
    ports:
      - "${APP_PORT:-8080}:80"
    environment:
      - API_KEY=${GEMINI_API_KEY}
      - LOKI_BACKEND_URL=${LOKI_URL:-http://192.168.20.96:3100}
    restart: always
